water_per_cup = int(200)
milk_per_cup = int(50)
coffee_beans_per_cup = int(15)

print("Write how many cups of coffee you will need:")
coffee_cups = int(input())
print("For {} cups of coffee you will need:".format(coffee_cups))
print("{} ml of water".format(coffee_cups * water_per_cup))
print("{} ml of milk".format(coffee_cups * milk_per_cup))
print("{} g of coffee beans".format(coffee_cups * coffee_beans_per_cup))
